name: Basic Workflow develop

on:
  push:
    branches:
      - main

jobs:
  run-unit-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

       

#triger


#push on main branch



    #1 unit test 
    

     
       #checkout code: 

          
       #run unit test
     

    # 2 build docker image and push
        # checkout code

        # build docker image
        
        #tag docker image with version
        
        #login in docker hub
        
        # push docker image

    # 3 deploy to vps
        
        #ssh connection to vps
        # pull docker image
        # run docker container